config/routes.rb
Rails.application.routes.draw do
  resources :people
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'people#index'

  get "intent", to:"people#intent"
  get "intentj", to:"people#intentj"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[ show edit update destroy ]

  # GET /people or /people.json
  def index
    @people = Person.all
 end
 
  # GET /people/1 or /people/1.json
  def show
  end

  def intent
  end

 def intentj
  p = Person.all
  pJson = p.to_json #had issues reading this in to the datatable 
  #  Rails.logger.info "to json"
  # Rails.logger.info pJson
   obj = {}
   p1 = {first_name:'kiyah', last_name:'rainer',id:1}
   p2 = {first_name:'von', last_name:'parrish',id:2}
   list = []
   list.push(p1)
   list.push(p2)


   @people = Person.all
 #  obj[:data] = @people.to_json
   obj[:data] = list

   Rails.logger.info obj
   render json: obj
end


  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people or /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to person_url(@person), notice: "Person was successfully created." }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to person_url(@person), notice: "Person was successfully updated." }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url, notice: "Person was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :phone, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Datatablesdemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/people/_dropdown.html.erb
<ul class="nav nav-tabs">
  <li id="one" role="presentation"><%= link_to "Regular Table", root_path %></li>
  <li id="two" role="presentation"><%= link_to "Json Table", intent_path %></li>
  <li id="three" role="presentation"><a href="/">reg2</a></li>
  <li id="four" role="presentation"><a href="/intent" >json2</a></li>

  <li class="dropdown active">
      <a class="dropdown-toggle" id="dLabel"  data-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">
        Dropdown trigger    <b class="caret"></b></a>
            <ul class="dropdown-menu pull-left" >
                <li class="active"><a class="dropdown-item" href="#table1" data-toggle="tab">table1</a></li>
                <li><a class="dropdown-item" href="#table2" data-toggle="tab">table2</a></li>
            </ul>
  </li>


  <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li><a href="#">Action</a></li>
    <li><a href="#">Another action</a></li>
    <li><a href="#">Something else here</a></li>
    <li role="separator" class="divider"></li>
    <li class="dropdown-header">Nav header</li>
    <li><a href="#">Separated link</a></li>
    <li><a href="#">One more separated link</a></li>
  </ul>
</li>


</ul>

<br/><br/>

<div class="tab-content">
    <div id="table1" class="tab-pane active"> table1</div>
    <div id="table2" class="tab-pane"> table2</div>
</div>

</br></br>

<!-- Large button group -->
<div class="btn-group">
  <button class="btn btn-default btn-lg dropdown-toggle" type="button" data-toggle="dropdown" 
           aria-haspopup="true" aria-expanded="false">
     Table <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Regular Table", root_path %></li>
    <li><%= link_to "Json Table", intent_path %></li>
    <li><a href="#" >Another action</a></li>
    <li><a href="#" >Something else here</a></li>
    <li role="separator" class="divider"></li>
    <li><a href="#">Separated link</a></li>
  </ul>
</div>

<script>

window.addEventListener('DOMContentLoaded', function(e){
    var activeId = localStorage.getItem("activeTab");
    if(activeId) {
        $("#"+activeId).addClass("active");
    }
    else {
        $("#one").addClass("active") //set the first tab by default
    }
   
    $(".nav li").on("click", function(e){
      //  alert('in clicke')
        var domElement = $(e.target).parent(".nav li");
        var domId = domElement.attr('id')
        localStorage.setItem("activeTab", domId); 
    })
});


if (typeof(Storage) !== "undefined"){
   // alert('Yay you have local/session storage')
}else{
   // alert('Sorry no web storage support...')
}


</script>

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if person.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :phone, style: "display: block" %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/people/_person.html.erb
<div id="<%= dom_id person %>">
  <p>
    <strong>First name:</strong>
    <%= person.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= person.last_name %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= person.phone %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= person.age %>
  </p>

</div>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Show this person", @person %> |
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>People Regular</h1>
<%= render 'dropdown' %>
<br/><br/>


<table id="ordersTable" class="table table-striped">
<thead>
<tr>
  <th>Firstname</th>
  <th>Lastname</th>
  <th></th>
</tr>
</thead>

<tbody>
   <% @people.each do |person| %>
    <tr>
      <td><%= person.first_name %></td>
      <td><%= person.last_name %></td>
      <td><%= link_to "View Person", person_path(person)  %></td>

    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New person", new_person_path %>
<script>
    window.addEventListener('DOMContentLoaded', function(e){
      var table1
      $(document).ready(function(){

        table1 = $("#ordersTable").DataTable({
          pageLength:50,
          order:[[0, 'desc']],
          columnDefs: [
            { targets: 1,
              render: function(data) {
                return  '<%= link_to "New person-config", new_person_path %>'
              }
            }   
          ]
        })
     });

     // not working
     $('#ordersTable tbody').on( 'click','tr', function ( s ) {
 
      console.log(table1.row(this).data())
     } );

    });


</script>

app/views/people/intent.html.erb
<h1>People Json</h1>
<%= render 'dropdown' %>
<br/><br/>


<table id="intentTable" class="table table-striped">
<thead>
<tr>
  <th>Firstname</th>
  <th>Lastname</th>
  <th>ID</th>
  </tr>
</thead>
 <tbody>
  </tbody>
</table>
    



<script>
    window.addEventListener('DOMContentLoaded', function(e){
      $(document).ready(function(){
        table1 = $("#intentTable").DataTable({
          ajax: "/intentj",
          processing: '<i class="fa fa-spinner fa-spin" style="font-size:24px;color:rgb(75, 183, 245);"></i>',

          columns: [
            { "data": "first_name" },
            { "data": "last_name" },
            { "data": "id" }
          ],
          columnDefs: [
            {
                targets:-1, // Start with the last
                render: function ( data, type, row, meta ) {
                    //console.log(row);
                    //data = '<%= link_to "Regular Table", root_path %>';
                    data = '<a href="/people/' + row.id + '">' + row.first_name + '</a>';
                    return data;
                }
            }
        ] 
        })
     });

    })

</script>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render "form", person: @person %>

<br>

<div>
  <%= link_to "Back to people", people_path %>
</div>

app/views/people/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @person %>

<div>
  <%= link_to "Edit this person", edit_person_path(@person) %> |
  <%= link_to "Back to people", people_path %>

  <%= button_to "Destroy this person", @person, method: :delete %>
</div>